variables:
  GIT_SSL_NO_VERIFY: "1"
  GIT_STRATEGY: "clone"
  B_VERSION: "cleep1"
  PATH_RELEASES: "/opt/releases/$B_VERSION/$CI_PROJECT_NAME/app"
  ARCH_NAME: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

stages:
  - compile
  - lint
  - xref
  - dialyze

job compile:
  stage: compile
  script:
    - make d_compile
  except:
    - master
    - tags

job lint:
  stage: lint
  script:
    - make d_lint
  except:
    - master
    - tags

job xref:
  stage: xref
  script:
    - make d_xref
  except:
    - master
    - tags

job dialyze:
  stage: dialyze
  script:
    - make d_dialyze
  except:
    - master
    - tags
